name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Java setup
        uses: actions/setup-java
        with:
          distribution: "temurin"
          java-version: "21
  



