name: Build and Deploy

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build docker image
        run: docker build -t ${{secrets.DOCKER_REGISTRY_USER}}/addtwonumbers:latest -f Dockerfile .

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
         username: ${{secrets.DOCKER_REGISTRY_USER}}
         password: ${{secrets.DOCKER_REGISTRY_PASS}}

      - name: List docker images
        run: docker image ls

      
        
